name: Build locale.g

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-locale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar Pipenv
        run: pip install pipenv

      - name: Instalar dependências
        run: pipenv install --dev --ignore-pipfile

      - name: Gerar locale.g
        run: pipenv run python tools/script.py --pack ./build/locale.g ./raw

      - name: Upload artefato locale.g
        uses: actions/upload-artifact@v4
        with:
          name: locale.g
          path: build/locale.g